import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/lib/app-context";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light">
      <body className="bg-white text-black antialiased">
        <AppProvider>
          {children}
          <Toaster 
          theme="light"
            position="top-right"     // optional: top-right is common & nice
            richColors               // optional: nicer colors
            closeButton              // optional: adds X button
            duration={3000}          // optional: auto-hide after 4s
          />
        </AppProvider>
      </body>
    </html>
  )
}

